"""Render findings[] (and an optional LLM narrative) into the client-facing Markdown report.
The table and totals are pure code; the narrative, when present, is the validated LLM output."""

from __future__ import annotations

from .schema import Finding, Report


def total_savings(findings: list[Finding]) -> float:
    return round(sum(f.monthly_savings_eur for f in findings), 2)


def _fmt(eur: float) -> str:
    return f"€{eur:,.2f}"


def _savings_cell(f: Finding) -> str:
    if f.savings_low_eur is not None and f.savings_high_eur is not None:
        return f"{_fmt(f.savings_low_eur)}–{_fmt(f.savings_high_eur)}"
    if f.monthly_savings_eur == 0:
        return "—"
    return _fmt(f.monthly_savings_eur)


def render_markdown(findings: list[Finding], report: Report | None = None) -> str:
    total = total_savings(findings)
    quantified = [f for f in findings if f.monthly_savings_eur > 0]
    lines: list[str] = []

    lines.append("# AWS FinOps Audit")
    lines.append("")
    lines.append(
        f"**Estimated addressable waste: {_fmt(total)}/month** "
        f"(~{_fmt(total * 12)}/year) across {len(findings)} findings."
    )
    lines.append("")
    lines.append(
        "> Savings are computed in code on public list prices (storage/networking are never "
        "Savings-Plan/RI-covered, so list price is the effective rate) and from AWS's own "
        "Cost Explorer / Compute Optimizer estimates for compute. Estimates assume no existing "
        "commitment covers the resource unless stated; review caveats before acting."
    )
    lines.append("")

    if report is not None:
        lines.append("## Executive summary")
        lines.append("")
        lines.append(report.executive_summary)
        lines.append("")

    lines.append("## Findings (prioritized: safe quick wins first)")
    lines.append("")
    lines.append("| # | Finding | Resource | Est. €/mo | Effort | Risk | Confidence |")
    lines.append("|---|---------|----------|-----------|--------|------|------------|")
    for i, f in enumerate(findings, 1):
        lines.append(
            f"| {i} | {f.title} | `{f.resource_id}` ({f.region}) | {_savings_cell(f)} "
            f"| {f.effort.value} | {f.risk.value} | {f.confidence.value} |"
        )
    lines.append("")

    if report is not None and report.recommendations:
        lines.append("## Recommended actions")
        lines.append("")
        by_id = {f.id: f for f in findings}
        for i, rec in enumerate(report.recommendations, 1):
            f = by_id.get(rec.finding_id)
            tag = f" — {_savings_cell(f)}/mo" if f else ""
            lines.append(f"### {i}. {rec.headline}{tag}")
            lines.append("")
            lines.append(rec.rationale)
            lines.append("")
            lines.append(f"**Action:** {rec.action}")
            if f and f.caveats:
                lines.append("")
                lines.append("_Caveats: " + "; ".join(f.caveats) + "_")
            lines.append("")

    lines.append("## Detail & caveats")
    lines.append("")
    for f in findings:
        lines.append(f"- **{f.title}** (`{f.resource_id}`, {f.region}) — {_savings_cell(f)}/mo. "
                     f"{f.evidence} _{f.confidence_reason}_")
        for c in f.caveats:
            lines.append(f"  - ⚠ {c}")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("*Generated by aws-finops-toolkit (read-only). No resources were modified.*")
    return "\n".join(lines)
